// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzw10sbDyNaDgCyH6qklRtUPdr6wFLSP4',
    appId: '1:428126162031:web:40b4c87153dacfc133519a',
    messagingSenderId: '428126162031',
    projectId: 'sereneanonymous-6d1eb',
    authDomain: 'sereneanonymous-6d1eb.firebaseapp.com',
    storageBucket: 'sereneanonymous-6d1eb.firebasestorage.app',
    measurementId: 'G-XZPMK86YWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp86vBJKQ5fcs1FnqdK30w9N1iZU45uAE',
    appId: '1:428126162031:android:d6c34c4b5f0a96b533519a',
    messagingSenderId: '428126162031',
    projectId: 'sereneanonymous-6d1eb',
    storageBucket: 'sereneanonymous-6d1eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuvrQ6xI3ZC-b2U_s-PrJAlKDj8_bVHzw',
    appId: '1:428126162031:ios:e77424e3cc7d3e6933519a',
    messagingSenderId: '428126162031',
    projectId: 'sereneanonymous-6d1eb',
    storageBucket: 'sereneanonymous-6d1eb.firebasestorage.app',
    androidClientId: '428126162031-91ftvp33ar5qo3arl7veji0eroqsb7e3.apps.googleusercontent.com',
    iosClientId: '428126162031-17g57rtu0t17b0bikov55agpguc0dlh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuvrQ6xI3ZC-b2U_s-PrJAlKDj8_bVHzw',
    appId: '1:428126162031:ios:e77424e3cc7d3e6933519a',
    messagingSenderId: '428126162031',
    projectId: 'sereneanonymous-6d1eb',
    storageBucket: 'sereneanonymous-6d1eb.firebasestorage.app',
    androidClientId: '428126162031-91ftvp33ar5qo3arl7veji0eroqsb7e3.apps.googleusercontent.com',
    iosClientId: '428126162031-17g57rtu0t17b0bikov55agpguc0dlh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzw10sbDyNaDgCyH6qklRtUPdr6wFLSP4',
    appId: '1:428126162031:web:54afadae4aba15a533519a',
    messagingSenderId: '428126162031',
    projectId: 'sereneanonymous-6d1eb',
    authDomain: 'sereneanonymous-6d1eb.firebaseapp.com',
    storageBucket: 'sereneanonymous-6d1eb.firebasestorage.app',
    measurementId: 'G-P1C5FPRY2R',
  );
}
